disabled_rules:
    - trailing_whitespace
    - identifier_name
    - nesting
    - multiple_closures_with_trailing_closure
opt_in_rules:
    - array_init
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - control_statement
    - empty_count
    - empty_string
    - first_where
    - for_where
    - function_default_parameter_at_end
    - mark
    - opening_brace
    - operator_usage_whitespace
    - override_in_extension
    - private_action
    - private_outlet
    - redundant_nil_coalescing
    - redundant_string_enum_value
    - redundant_type_annotation
    - return_arrow_whitespace
    - sorted_first_last
    - statement_position
    - static_operator
    - untyped_error_in_catch
    - unused_enumerated
    - unused_optional_binding
    - vertical_parameter_alignment_on_call
    - yoda_condition
    - empty_enum_arguments
    - force_unwrapping
    - convenience_type
    - toggle_bool
    - unneeded_parentheses_in_closure_argument
    - empty_collection_literal
    - contains_over_first_not_nil

analyzer_rules:
    - unused_import
    - unused_declaration

included:
    - newhome

excluded:
    - Pods
    - Carthage

force_cast: warning
force_try:
    severity: warning

force_unwrapping: warning

closure_end_indentation: warning
closure_parameter_position: warning
unneeded_parentheses_in_closure_argument: warning
closure_spacing: warning
convenience_type: warning
empty_collection_literal: warning
empty_parameters: warning
empty_parentheses_with_trailing_closure: warning
empty_string: warning
redundant_void_return: warning
toggle_bool: warning
weak_delegate: warning
vertical_parameter_alignment_on_call: warning

large_tuple:
    warning: 4
    error: 5

cyclomatic_complexity:
    warning: 3 # three nested ifs are acceptable
    error: 5   # six nested ifs shows warning, 6 causes compile error
    ignores_case_statements: true

file_length:
    warning: 500
    error: 700
    
type_name:
    max_length: 60

line_length:
    ignores_comments: true
    ignores_function_declarations: true

custom_rules:
    review_needed:
        regex: "([Rr]eview)"
        message: "This should be improved"
        match_kinds:
          - comment
        severity: warning
